sonar.projectKey=abvgzxn_frontend_project_46
sonar.organization=abvgzxn

# Исходный код
sonar.sources=src

# Тесты
sonar.tests=__tests__
sonar.test.inclusions=__tests__/**/*.test.js

# Отчёты о покрытии
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Исключаем ненужные файлы
sonar.exclusions=coverage/**, __fixtures__/**, **/*.test.js, node_modules/**

# Настройки для SonarCloud
sonar.host.url=https://sonarcloud.io
